name: ArgentumcraftCustomTweaks
version: 1.0.0
description: A collection of simple tweaks for the Argentumcraft server
author: austinv11
website: argentumcraft.enjin.com
 
main: com.enjin.argentumcraft.ArgentumcraftCustomTweaks.ArgentumcraftCustomTweaks
commands:
   givefreezeitem:
      description: Gives the sender an item used to freeze things
      usage: /<command> <optional:player>
      permission: ArgentumcraftCustomTweaks.givefreezeitem
      permission-message: You don't have permission

permissions:
   ArgentumcraftCustomTweaks.*:
        description: Gives access to all ArgentumcraftCustomTweaks permissions
   ArgentumcraftCustomTweaks.easterEggSignAbility:
        description: Gives the ability to create an easter egg sign
   ArgentumcraftCustomTweaks.giveFreezeItem:
      description: Gives the sender an item used to freeze things
   ArgentumcraftCustomTweaks.freezeBypass:
      description: Determines whether the player can bypass the frozen effect